### ISSUE TITLE
Some instances not blocked

### ISSUE THREAD

**Issue by ghost** [theZacAttacks/silence#7]
fediverse.network lists e.g. `develop.gab.com`, but this wasn't blocked by this script. neither was `not-develop.gab.com`. it didn't output any errors or anything, so i'm not sure why!

**Comment by compufox** [comment]
Were those instances already blocked?

**Comment by ghost** [comment]
i'm like... 80% sure that `not-develop.gab.com` was not blocked. sorry, i know that's not a very useful bug report!

does the script not block instances that have been blocked in the past?

**Comment by compufox** [comment]
Yeah, it checks to see if the instance is already blocked before it tries to create a new block. 

An easy way to tell if the script blocked a domain is by going into the domain block page and see if that domain suspension says "rejecting media" and "rejecting reports"  (assuming you dont usually check those options when suspending an instance)

**Comment by ghost** [comment]
Ah, they definitely were not blocked when I ran the script. I mean that they may have been in the past. After running the script, they're still not on my blocklist.

**Comment by compufox** [comment]
Oh, this could be something to do with how blocks are handled in newer mastodon releases. 

I think it autoblocks subdomains if the main domain is blocked. 

I'll look into it more, but that's my theory for now

**Comment by compufox** [comment]
okay! so i did a quick test and i do think this whats happening
![github_issue7](https://user-images.githubusercontent.com/1060898/62428474-6bd3b480-b6d0-11e9-9a65-c92a3c0ac989.png)

I'll make sure to add a note about it in the readme, and if you're comfortable with this answer I'll close this issue!

**Comment by ghost** [comment]
Ah right, neat! Yes, thank you :)
